#!/bin/bash
################################################################################
# Detect Existing Organization Policies
#
# This script queries GCP for existing organization policies and generates
# a terraform.tfvars file with the existing_policies variable populated.
# This enables incremental compliance where policies are only created if
# they don't already exist.
#
# Usage:
#   ./scripts/detect_existing_policies.sh
#
# Prerequisites:
#   - gcloud CLI installed and authenticated
#   - Organization ID or Folder ID configured in terraform.tfvars
################################################################################

set -e

echo "========================================="
echo "Detect Existing Organization Policies"
echo "========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get organization/folder from terraform.tfvars
if [ ! -f "terraform.tfvars" ]; then
  echo -e "${RED}❌ Error: terraform.tfvars not found${NC}"
  echo "Please create terraform.tfvars first"
  exit 1
fi

# Extract organization_id and folder_id from terraform.tfvars
ORG_ID=$(grep 'organization_id' terraform.tfvars | cut -d'"' -f2 | tr -d ' ')
FOLDER_ID=$(grep 'folder_id' terraform.tfvars | cut -d'"' -f2 | tr -d ' ' | grep -v '^#' || echo "")

if [ -z "$ORG_ID" ]; then
  echo -e "${RED}❌ Error: Could not determine organization_id from terraform.tfvars${NC}"
  exit 1
fi

# Determine parent
if [ -n "$FOLDER_ID" ] && [ "$FOLDER_ID" != "null" ]; then
  PARENT="folders/$FOLDER_ID"
  PARENT_FLAG="--folder=$FOLDER_ID"
  echo -e "Parent: ${GREEN}$PARENT${NC}"
else
  PARENT="organizations/$ORG_ID"
  PARENT_FLAG="--organization=$ORG_ID"
  echo -e "Parent: ${GREEN}$PARENT${NC}"
fi

echo ""

# List of all policies managed by this module
# Format: constraint_name
POLICIES=(
  # Security Controls
  "constraints/iam.disableServiceAccountKeyCreation"
  "constraints/iam.automaticIamGrantsForDefaultServiceAccounts"
  "constraints/iam.allowedPolicyMemberDomains"
  "constraints/compute.vmExternalIpAccess"
  "constraints/compute.requireOsLogin"
  "constraints/compute.requireShieldedVm"
  "constraints/sql.restrictPublicIp"
  "constraints/sql.restrictAuthorizedNetworks"
  
  # Availability Controls
  "constraints/gcp.resourceLocations"
  
  # Confidentiality Controls
  "constraints/storage.uniformBucketLevelAccess"
  "constraints/storage.publicAccessPrevention"
  "constraints/gcp.restrictNonCmekServices"
  "constraints/compute.restrictVpcPeering"
)

FOUND_POLICIES=()
MISSING_POLICIES=()

echo "Checking for existing policies..."
echo ""

for constraint in "${POLICIES[@]}"; do
  # Extract just the constraint name without "constraints/" prefix
  constraint_name="${constraint#constraints/}"
  
  # Check if policy exists
  if gcloud org-policies describe "$constraint_name" $PARENT_FLAG &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} Found: $constraint"
    FOUND_POLICIES+=("$constraint")
  else
    echo -e "  ${YELLOW}○${NC} Not found: $constraint"
    MISSING_POLICIES+=("$constraint")
  fi
done

echo ""
echo "========================================="
echo "Summary"
echo "========================================="
echo -e "Existing policies: ${GREEN}${#FOUND_POLICIES[@]}${NC}"
echo -e "Missing policies:  ${YELLOW}${#MISSING_POLICIES[@]}${NC}"
echo ""

# Generate terraform.tfvars content
TFVARS_FILE="terraform.tfvars.existing_policies"

echo "Generating $TFVARS_FILE..."

cat > "$TFVARS_FILE" << 'EOF'
# Existing Organization Policies
# Auto-generated by scripts/detect_existing_policies.sh
# This map prevents Terraform from trying to create policies that already exist

existing_policies = {
EOF

# Add each found policy to the map
for constraint in "${FOUND_POLICIES[@]}"; do
  echo "  \"$constraint\" = {}" >> "$TFVARS_FILE"
done

cat >> "$TFVARS_FILE" << 'EOF'
}
EOF

echo -e "${GREEN}✓${NC} Generated $TFVARS_FILE"
echo ""

# Instructions
echo "========================================="
echo "Next Steps"
echo "========================================="
echo ""
echo "1. Review the generated file:"
echo -e "   ${YELLOW}cat $TFVARS_FILE${NC}"
echo ""
echo "2. Merge with your terraform.tfvars:"
echo -e "   ${YELLOW}cat $TFVARS_FILE >> terraform.tfvars${NC}"
echo ""
echo "   Or manually copy the existing_policies block"
echo ""
echo "3. Run terraform plan:"
echo -e "   ${YELLOW}terraform plan${NC}"
echo ""
echo "4. Terraform will:"
echo -e "   - ${GREEN}Skip${NC} creating ${#FOUND_POLICIES[@]} existing policies"
echo -e "   - ${YELLOW}Create${NC} ${#MISSING_POLICIES[@]} missing policies"
echo ""

if [ ${#FOUND_POLICIES[@]} -gt 0 ]; then
  echo -e "${GREEN}✓ Incremental compliance enabled!${NC}"
  echo "  Existing policies will not be recreated"
else
  echo -e "${YELLOW}⚠ No existing policies found${NC}"
  echo "  All policies will be created on terraform apply"
fi

echo ""
echo "========================================="
